-- ============================================================================
-- Gagyo Backend Schema - Auth Hooks Migration
-- ============================================================================
-- This migration creates auth hooks to inject custom JWT claims for
-- tenant_id and role based on the user's active membership.
--
-- Custom claims enable RLS policies to efficiently check user context
-- without additional database queries.
--
-- Expected JWT claims after this migration:
--   - tenant_id: UUID of the user's active tenant (for single-tenant context)
--   - role: user's role in that tenant ('member', 'small_group_leader', etc.)
--
-- See: claude_docs/04_multi_tenant_model.md for auth architecture
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Helper Function: Get user's default tenant and role
-- ----------------------------------------------------------------------------
-- For users with multiple active memberships, returns the first one.
-- Applications should explicitly set tenant context via RPC for multi-tenant use.

CREATE OR REPLACE FUNCTION get_user_default_context(p_user_id UUID)
RETURNS TABLE(tenant_id UUID, role TEXT) AS $$
BEGIN
  RETURN QUERY
  SELECT m.tenant_id, m.role
  FROM memberships m
  WHERE m.user_id = p_user_id
    AND m.status = 'active'
  ORDER BY m.created_at ASC
  LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

-- ----------------------------------------------------------------------------
-- Auth Hook: Custom Access Token Hook
-- ----------------------------------------------------------------------------
-- This function is called by Supabase Auth when generating access tokens.
-- It injects tenant_id and role claims into the JWT.
--
-- Note: This hook must be registered in Supabase Auth configuration:
-- Dashboard > Authentication > Hooks > Access Token Hook
--
-- Hook configuration:
--   - Hook Name: custom_access_token_hook
--   - Enabled: true
--   - Secret: (auto-generated by Supabase)

CREATE OR REPLACE FUNCTION auth.custom_access_token_hook(event jsonb)
RETURNS jsonb AS $$
DECLARE
  v_user_id UUID;
  v_claim jsonb;
  v_membership RECORD;
BEGIN
  -- Extract user_id from the event
  v_user_id := (event->>'user_id')::UUID;

  -- If no user_id, return empty claims
  IF v_user_id IS NULL THEN
    RETURN '{}'::jsonb;
  END IF;

  -- Get user's default tenant and role
  SELECT * INTO v_membership
  FROM get_user_default_context(v_user_id)
  LIMIT 1;

  -- Build custom claims
  v_claim := jsonb_build_object(
    'tenant_id', v_membership.tenant_id,
    'role', v_membership.role,
    'email', (SELECT email FROM auth.users WHERE id = v_user_id)
  );

  RETURN v_claim;
EXCEPTION
  WHEN OTHERS THEN
    -- On any error, return empty claims rather than failing auth
    RETURN jsonb_build_object(
      'tenant_id', NULL,
      'role', NULL
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute on the hook to authenticator role
GRANT EXECUTE ON FUNCTION auth.custom_access_token_hook(jsonb) TO authenticator;

-- ----------------------------------------------------------------------------
-- Helper Function: Get current tenant_id from JWT claims
-- ----------------------------------------------------------------------------
-- Provides fallback to database lookup if JWT claim is missing.

CREATE OR REPLACE FUNCTION get_current_tenant_id()
RETURNS UUID AS $$
DECLARE
  v_tenant_id UUID;
BEGIN
  -- First try to get from JWT custom claims
  v_tenant_id := (auth.jwt()->>'tenant_id')::UUID;

  -- If claim is present and valid, return it
  IF v_tenant_id IS NOT NULL THEN
    RETURN v_tenant_id;
  END IF;

  -- Fallback: get from memberships (for backward compatibility)
  SELECT m.tenant_id INTO v_tenant_id
  FROM memberships m
  WHERE m.user_id = auth.uid()
    AND m.status = 'active'
  ORDER BY m.created_at ASC
  LIMIT 1;

  RETURN v_tenant_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

-- ----------------------------------------------------------------------------
-- Helper Function: Get current role from JWT claims
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION get_current_role()
RETURNS TEXT AS $$
DECLARE
  v_role TEXT;
BEGIN
  -- First try to get from JWT custom claims
  v_role := auth.jwt()->>'role';

  -- If claim is present and valid, return it
  IF v_role IS NOT NULL THEN
    RETURN v_role;
  END IF;

  -- Fallback: get from memberships (for backward compatibility)
  SELECT m.role INTO v_role
  FROM memberships m
  WHERE m.user_id = auth.uid()
    AND m.status = 'active'
  ORDER BY m.created_at ASC
  LIMIT 1;

  RETURN v_role;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

-- ============================================================================
-- Documentation for JWT Claims
-- ============================================================================
--
-- After registering the hook in Supabase Auth, access tokens will include:
--
-- {
--   "aud": "authenticated",
--   "role": "authenticated",
--   "custom_claims": {
--     "tenant_id": "uuid-of-users-tenant",
--     "role": "member|small_group_leader|zone_leader|pastor|admin",
--     "email": "user@example.com"
--   },
--   ...
-- }
--
-- Accessing claims in SQL:
--   - tenant_id: (auth.jwt()->>'tenant_id')::UUID
--   - role: auth.jwt()->>'role'
--
-- Accessing claims via helper functions:
--   - tenant_id: get_current_tenant_id()
--   - role: get_current_role()
--
-- Verification query:
--   SELECT auth.jwt();
--
-- ============================================================================
